version: '3.9'

# Services
services:
 # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb
# Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 88:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
  # MariaDB Service
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: skillopdracht
      MYSQL_USER: rayan
      MYSQL_PASSWORD: dhbfgaiufbuiahf
      MYSQL_ROOT_PASSWORD: 2hifgi2ghfiu2hg
    ports:
      - 3308:3306

  # php myadmin in an external image
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: rayan
      PMA_PASSWORD: dhbfgaiufbuiahf
    ports:
      - "1088:80"

# Volumes
volumes:
  mysqldata: